In [1]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [ ]:
# data_structure : [Restaurent_Id , 2021 , 2022 , 2023 , 2024]
import numpy as np
sales_data =np.array([

    [1,150000,180000,220000,250000], # Paradise Biriyani
    [2,120000,140000,160000,190000], # Pizza Hub
    [3,200000,230000,260000,300000], # Burger Point 
    [4,180000,210000,240000,270000], # Chai Point
    [5,160000,185000,200000,230000], # Coffe House

])
print("==== Zomato sales Analysis ==== ")
print("\n Sales Data shape :",sales_data.shape) # prints the number of row and column
print("Sample data for 1st 3 rows : \n",sales_data[:,1:]) # Take all rows Skip column 0 (Restaurant ID) Return columns

# Print the sum of the sales
print(f" \n sum of rows : {sales_data[:,1:].sum(axis=1)}") # prints the row elements
print(f" \n sum of columns : {sales_data[:, 1:].sum(axis=0)}") # Prints the columns

# [:, 1:] First : means take all the rows secnd 1: means start from column index 1

==== Zomato sales Analysis ==== 

 Sales Data shape : (5, 5)
Sample data for 1st 3 rows : 
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 200000 230000]]
 
 sum of rows : [800000 610000 990000 900000 775000]
 
 sum of columns : [     15  810000  945000 1080000 1240000]


## Minumym sales per restaurent

In [2]:
import numpy as np
sales_data =np.array([

    [1,150000,180000,220000,250000], # Paradise Biriyani
    [2,120000,140000,160000,190000], # Pizza Hub
    [3,200000,230000,260000,300000], # Burger Point 
    [4,180000,210000,240000,270000], # Chai Point
    [5,160000,185000,200000,230000], # Coffe House

])

print(sales_data[:, 1:].sum(axis=0))

[ 810000  945000 1080000 1240000]
