# Practice Numpy for Better Understanding

In [1]:
# Create a NumPy array from the following list.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
a1 = np.array([1,2,3,4])
a2 = np.array([1.1,2.2,3.3,4.4])
print(a1.dtype)
print(a2.dtype)

print(a1.itemsize)
print(a2.itemsize)

print(a1.shape)
print(f"Dimenstion : {a1.ndim}")

int64
float64
8
8
(4,)
(4,)
Dimenstion : 1


In [ ]:
# A 1D array containing 10 zeros.
import numpy as np
arr = np.zeros((1,10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
# A 3 × 3 matrix containing ones.
arr1 = np.ones((3,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
