# Practice Numpy for Better Understanding

In [1]:
# Create a NumPy array from the following list.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [16]:
import numpy as np
a1 = np.array([[1,2,3,4],
               [4,5,6,7,]])
a2 = np.array([1.1,2.2,3.3,4.4])
print(a1.dtype)
print(a2.dtype)

print(a1.itemsize)
print(a2.itemsize)

print(f"The shape is : {a1.shape}")
print("There are ",a1.size,"elements in a1")

print(f"Dimenstion : {a1.ndim}")

int64
float64
8
8
The shape is : (2, 4)
There are  8 elements in a1
Dimenstion : 2


In [ ]:
# A 1D array containing 10 zeros.
import numpy as np
arr = np.zeros((1,10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
# A 3 × 3 matrix containing ones.
arr1 = np.ones((3,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# Create a NumPy array containing numbers from 1 to 50.
arra = np.arange(0,51)
print(arra)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [25]:
# Create an array containing numbers from 1 to 12

array = np.arange(1,13)
print(array)
print("Reshaped array : \n",array.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
