# Practice Numpy for Better Understanding

In [1]:
# Create a NumPy array from the following list.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [16]:
import numpy as np
a1 = np.array([[1,2,3,4],
               [4,5,6,7,]])
a2 = np.array([1.1,2.2,3.3,4.4])
print(a1.dtype)
print(a2.dtype)

print(a1.itemsize)
print(a2.itemsize)

print(f"The shape is : {a1.shape}")
print("There are ",a1.size,"elements in a1")

print(f"Dimenstion : {a1.ndim}")

int64
float64
8
8
The shape is : (2, 4)
There are  8 elements in a1
Dimenstion : 2


In [ ]:
# A 1D array containing 10 zeros.
import numpy as np
arr = np.zeros((1,10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
# A 3 × 3 matrix containing ones.
arr1 = np.ones((3,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# Create a NumPy array containing numbers from 1 to 50.
arra = np.arange(0,51)
print(arra)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [27]:
# Create an array containing numbers from 1 to 12

array = np.arange(1,13)
print(array)
print("Reshaped array : \n",array.reshape(3,4))
print("Reshaped again : \n",array.reshape(2,6))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped again : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [40]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("First element is :",arr[0])
print("Last element is :",arr[-1])
print("Last element is :",arr[-1:])
print("Elements from 1 to 4 :",arr[1:5])
print("Reversed array is :",arr[::-1])

First element is : 10
Last element is : 60
Last element is : [60]
Elements from 1 to 4 : [20 30 40 50]
Reversed array is : [60 50 40 30 20 10]


In [49]:
# Given an 2D array find 50,70,30 ,(First row),(last Row),(second row)
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0,2])
print(arr[1,1])
print(arr[2,0])

print("First Row is :",arr[0])
print("Second Row is :",arr[1])
print("Second Row is :",arr[-1])


30
50
70
First Row is : [10 20 30]
Second Row is : [40 50 60]
Second Row is : [70 80 90]


In [ ]:
import numpy as np

arr = np.array([2, 4, 6, 8, 10])
for i in range(len(arr)):
    print(arr[i] + 5)


7
9
11
13
15


In [2]:
import numpy as np
marks = np.array([78, 85, 92, 67, 88, 95, 72])
print(marks.sum(axis=0))
print(marks.mean(axis=0))
print(marks.max(axis=0))
print(marks.min(axis=0))
print(marks.std())

577
82.42857142857143
95
67
9.663734014450151


In [ ]:
# Boolean filtering
import numpy as np
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A+B)


[[ 6  8]
 [10 12]]
